-- HD2-Addon: mods/hpmg/dl_hunt
--
-- L2.6: dl_probe and dl_dump merged, with the two things they got wrong fixed.
--
-- WHAT WENT WRONG BEFORE
--   dl_probe capped a buffer at 512 instances and 64 MB, then silently dropped
--   anything larger. generated_entities.dl_bin is 45.6 MB and is where weapon
--   definitions almost certainly live, so the one buffer that mattered most may
--   have been rejected without leaving a trace. A scanner that only reports
--   successes cannot tell you why it failed. This one reports near misses:
--   anything carrying a valid 'LDLD' header that was then thrown away, and the
--   reason it was thrown away.
--
--   dl_probe also scanned once, at whatever moment the first update tick ran.
--   Settings buffers load lazily, so a main-menu scan never sees mission data.
--   This rescans on an interval and dumps buffers as they appear, which lets a
--   single session cover the menu and then a mission.
--
-- Reads process memory only. Writes nothing back.

if rawget(_G, 'HpmgDlHunt') then return end

local ffi = require('ffi')

local BUILD = {
    revision = 'dl_hunt-2',
    exe_sha256 = 'A09FF52663E73B94FB0CAC0DCB5BA84FFD10ECF44F74A8921AC66AF923988CC3',
    game_sha256 = 'CC75948D90FDFDE259DCB519E9933DB7FFA3CCB281CE4FB89E6B1B011557470C',
}

local GLOBALS = {rva = 0x02394000, size = 7622788}
local DL_MAGIC = 0x444C444C

-- Raised far past anything a settings file should need. The point is no longer
-- to be strict, it is to find out what is actually there.
local MAX_INSTANCES = 262144
local MAX_TOTAL = 128 * 1024 * 1024
local MAX_DUMP = 48 * 1024 * 1024

local CHUNK = 65536
local CHUNKS_PER_TICK = 8
local PROBES_PER_TICK = 3000
local RESCAN_TICKS = 1800

-- Sweep budget. 2 MB per tick keeps the stutter small; a 45 MB blob has to sit
-- in a region at least that big, so tiny regions are not worth reading at all.
local SWEEP_BYTES_PER_TICK = 2 * 1024 * 1024
local SWEEP_MIN_REGION = 1024 * 1024

-- Buffers worth writing to disk when they show up, by fingerprinted name.
local DUMP_THESE = {
    entities = true,
    entity_deltas = true,
    projectile_settings = true,
    damage_settings = true,
    stratagem_settings = true,
    weapon_customization_settings = true,
    explosion_settings = true,
    hit_effect_settings = true,
}

-- Generated by tools/gen_fingerprints.py; decrypted size -> settings file.
local FINGERPRINTS = {
    [24] = 'resource_swap', [108] = 'layer_package_indirection_settings',
    [116] = 'body_settings', [133] = 'stratagem_upgrade_settings',
    [180] = 'add_resource_dependencies', [364] = 'corporation_logos',
    [412] = 'route_settings', [480] = 'policy_settings', [604] = 'font_lookup',
    [812] = 'candidate_descs', [1124] = 'video_ui_settings',
    [1468] = 'distant_war_effect_settings', [1708] = 'arc_settings',
    [1764] = 'modifier_settings', [2172] = 'video_flow_settings',
    [3404] = 'beam_settings', [3728] = 'customization_passive_bonuses',
    [3948] = 'language_settings', [5980] = 'font_settings',
    [8716] = 'scenario_settings', [10014] = 'generation_settings',
    [10908] = 'status_effect_settings', [12062] = 'environment_settings',
    [12484] = 'sky_settings', [14444] = 'collision_event_settings',
    [16964] = 'planet_types_settings', [24508] = 'unit_customization_settings',
    [24636] = 'weather_color_set_settings', [28784] = 'weapon_customization_settings',
    [33146] = 'planet_override_settings', [48664] = 'damage_settings',
    [57164] = 'hit_effect_settings', [61485] = 'planet_region_settings',
    [61716] = 'unit_effect_settings', [66388] = 'explosion_settings',
    [79296] = 'stratagem_settings', [84489] = 'satellite_groups',
    [91764] = 'solar_system_settings', [93340] = 'projectile_settings',
    [142067] = 'galactic_presence_settings', [165268] = 'animation_event_trigger_settings',
    [213482] = 'weather_settings', [264723] = 'region_settings',
    [303564] = 'surface_effect_settings', [330082] = 'entity_deltas',
    [368228] = 'credits_settings', [375748] = 'customization_armor_sets',
    [393025] = 'location_groups', [481676] = 'planet_data', [512495] = 'zone_data',
    [673740] = 'stamp_settings', [1574628] = 'planet_territory_graphs',
    [1630059] = 'destruction_settings', [45630790] = 'entities',
}

local state = {
    revision = BUILD.revision,
    phase = 'waiting_for_update',
    updates = 0, cycles = 0, candidates = 0, probed = 0,
    hits = 0, near_misses = 0, dumped = 0,
    sweep_regions = 0, sweep_bytes = 0, sweep_hits = 0,
    found = {},      -- rva -> description
    rejects = {},    -- reason -> count
    files = {},
}
rawset(_G, 'HpmgDlHunt', state)

local function report(message)
    print('[HpmgDlHunt] ' .. BUILD.revision .. ': ' .. message)
end

local function create_api()
    assert(ffi.abi('64bit'), 'Windows x64 is required')
    ffi.cdef [[
        void *GetModuleHandleA(const char *name);
        uint32_t GetModuleFileNameW(void *module, uint16_t *path, uint32_t capacity);
        void *GetCurrentProcess(void);
        int ReadProcessMemory(void *process, const void *address, void *buffer, size_t size, size_t *read);
        void *CreateFileW(const uint16_t *path, uint32_t access, uint32_t share, void *security,
                          uint32_t disposition, uint32_t flags, void *template_file);
        int ReadFile(void *file, void *buffer, uint32_t size, uint32_t *read, void *overlapped);
        int CloseHandle(void *handle);
        int32_t BCryptOpenAlgorithmProvider(void **algorithm, const uint16_t *name,
                                            const uint16_t *provider, uint32_t flags);
        int32_t BCryptCloseAlgorithmProvider(void *algorithm, uint32_t flags);
        int32_t BCryptCreateHash(void *algorithm, void **hash, void *object, uint32_t object_size,
                                 const void *secret, uint32_t secret_size, uint32_t flags);
        int32_t BCryptHashData(void *hash, const void *data, uint32_t size, uint32_t flags);
        int32_t BCryptFinishHash(void *hash, void *digest, uint32_t size, uint32_t flags);
        int32_t BCryptDestroyHash(void *hash);
        typedef struct {
            void *base; void *allocation_base; uint32_t allocation_protection;
            uint16_t partition; uint16_t reserved; size_t size;
            uint32_t state; uint32_t protection; uint32_t type;
        } HpmgMemoryRegion;
        size_t VirtualQuery(const void *address, void *region, size_t size);
    ]]
    local kernel, bcrypt = ffi.load('kernel32'), ffi.load('bcrypt')
    local process = kernel.GetCurrentProcess()
    local api = {}

    local scan = ffi.new('uint8_t[?]', CHUNK)
    local scan_words = ffi.cast('uint64_t *', scan)
    local small = ffi.new('uint8_t[64]')
    local small_words = ffi.cast('uint32_t *', small)
    local count = ffi.new('size_t[1]')
    local big                      -- allocated on first dump; 48 MB is not cheap

    function api.module(name)
        local handle = kernel.GetModuleHandleA(name)
        if handle == nil then return nil end
        return ffi.cast('uint8_t *', handle)
    end

    function api.read_chunk(address, size)
        if kernel.ReadProcessMemory(process, address, scan, size, count) == 0 then return false end
        return count[0] == size
    end

    function api.word(index) return scan_words[index] end

    -- Handed out whole rather than read through an accessor: the sweep compares
    -- half a million lanes per tick, and a function call per lane is the
    -- difference between a few milliseconds and a visible hitch.
    local scan_words32 = ffi.cast('uint32_t *', scan)
    function api.scan32() return scan_words32 end

    function api.read_header(address, size)
        if size > 64 then return false end
        if kernel.ReadProcessMemory(process, address, small, size, count) == 0 then return false end
        return count[0] == size
    end

    function api.header(index) return small_words[index] end

    function api.capture(address, size, sink)
        if size < 1 or size > MAX_DUMP then return false, 'size out of range' end
        if not big then big = ffi.new('uint8_t[?]', MAX_DUMP) end
        if kernel.ReadProcessMemory(process, address, big, size, count) == 0 then
            return false, 'read failed'
        end
        if count[0] ~= size then return false, 'short read' end
        -- Write in slices: one 45 MB Lua string would be a large, pointless copy.
        local offset = 0
        while offset < size do
            local slice = math.min(1048576, size - offset)
            sink(ffi.string(big + offset, slice))
            offset = offset + slice
        end
        return true
    end

    -- Committed private read/write regions, largest first. A 45 MB settings
    -- blob cannot hide in a small region, so size ordering finds the big
    -- targets long before the scan has to grind through the small ones.
    function api.regions(minimum)
        local region = ffi.new('HpmgMemoryRegion[1]')
        local size = ffi.sizeof(region[0])
        local found = {}
        local cursor = ffi.cast('uint8_t *', 0x10000ULL)
        local limit = ffi.cast('uint8_t *', 0x7FFFFFFF0000ULL)
        local guard = 0
        while cursor < limit do
            guard = guard + 1
            if guard > 200000 then break end
            if kernel.VirtualQuery(cursor, region, size) ~= size then break end
            local length = tonumber(region[0].size)
            if length <= 0 then break end
            -- MEM_COMMIT, MEM_PRIVATE, and writable or read-only data pages.
            if region[0].state == 0x1000 and region[0].type == 0x20000
                and (region[0].protection == 4 or region[0].protection == 2)
                and length >= minimum then
                -- Cast away void *: LuaJIT will not do arithmetic on it, and
                -- the sweep advances through this base byte by byte.
                found[#found + 1] = {base = ffi.cast('uint8_t *', region[0].base), size = length}
            end
            cursor = cursor + length
        end
        table.sort(found, function(a, b) return a.size > b.size end)
        return found
    end

    function api.module_hash(module)
        local path = ffi.new('uint16_t[32768]')
        local length = kernel.GetModuleFileNameW(module, path, 32768)
        assert(length > 0 and length < 32768, 'Cannot resolve module file')
        local file = kernel.CreateFileW(path, 0x80000000, 7, nil, 3, 0x08000000, nil)
        assert(file ~= ffi.cast('void *', -1), 'Cannot read module file')
        local algorithm, hash = ffi.new('void *[1]'), ffi.new('void *[1]')
        local ok, result = pcall(function()
            local name = ffi.new('uint16_t[7]', {83, 72, 65, 50, 53, 54, 0})
            assert(bcrypt.BCryptOpenAlgorithmProvider(algorithm, name, nil, 0) == 0, 'SHA256 unavailable')
            assert(bcrypt.BCryptCreateHash(algorithm[0], hash, nil, 0, nil, 0, 0) == 0, 'SHA256 creation failed')
            local buffer, read = ffi.new('uint8_t[1048576]'), ffi.new('uint32_t[1]')
            while true do
                assert(kernel.ReadFile(file, buffer, 1048576, read, nil) ~= 0, 'Module file read failed')
                if read[0] == 0 then break end
                assert(bcrypt.BCryptHashData(hash[0], buffer, read[0], 0) == 0, 'SHA256 update failed')
            end
            local digest, hex = ffi.new('uint8_t[32]'), {}
            assert(bcrypt.BCryptFinishHash(hash[0], digest, 32, 0) == 0, 'SHA256 finish failed')
            for i = 0, 31 do hex[#hex + 1] = string.format('%02X', digest[i]) end
            return table.concat(hex)
        end)
        if hash[0] ~= nil then bcrypt.BCryptDestroyHash(hash[0]) end
        if algorithm[0] ~= nil then bcrypt.BCryptCloseAlgorithmProvider(algorithm[0], 0) end
        kernel.CloseHandle(file)
        if not ok then error(result) end
        return result
    end

    return api
end

-- Returns total, type_id, instances, mixed  -- or nil, reason, had_header.
-- had_header says the candidate really did carry an 'LDLD' header, which is
-- what separates a near miss worth reporting from ordinary random memory.
local function measure(api, address)
    if not api.read_header(address, 28) then return nil, 'unreadable', false end
    if api.header(1) ~= DL_MAGIC then return nil, 'no magic', false end
    local had = true
    if api.header(2) ~= 1 then return nil, 'version ' .. api.header(2), had end
    local instances = api.header(0)
    if instances < 1 then return nil, 'zero instances', had end
    if instances > MAX_INSTANCES then
        return nil, 'instance cap: ' .. instances, had
    end
    if api.header(5) ~= 1 then return nil, 'not 64-bit', had end
    if api.header(6) ~= 0 then return nil, 'reserved set', had end

    local type_id = api.header(3)
    local offset, mixed = 4, false
    for index = 1, instances do
        if not api.read_header(address + offset, 24) then
            return nil, string.format('chain unreadable at instance %d/%d', index, instances), had
        end
        if api.header(0) ~= DL_MAGIC then
            return nil, string.format('chain magic at instance %d/%d', index, instances), had
        end
        if api.header(1) ~= 1 then return nil, 'chain version', had end
        if api.header(2) ~= type_id then mixed = true end
        offset = offset + 24 + api.header(3)
        if offset > MAX_TOTAL then return nil, 'total cap', had end
    end
    return offset, type_id, instances, mixed
end

local function note_reject(state, reason)
    state.near_misses = state.near_misses + 1
    state.rejects[reason] = (state.rejects[reason] or 0) + 1
end

local function log_directory(loader)
    if loader and loader.log_directory then return loader.log_directory end
    if loader and loader.open_log then
        local probe = loader.open_log('HpmgDlHunt.log')
        if probe then probe:close() end
        return loader.log_directory
    end
end

local function write_dump(api, state, name, address, total, type_id, instances)
    local loader = rawget(_G, 'CowboyBingusModLoader')
    local directory = log_directory(loader)
    if not directory then return false, 'no log directory' end
    local path = directory .. '/HpmgDump_' .. name .. '.bin'
    local file, reason = io.open(path, 'wb')
    if not file then return false, tostring(reason) end

    local header = ffi.new('uint8_t[32]')
    ffi.copy(header, 'HPMGDUMP', 8)
    local words = ffi.cast('uint32_t *', header + 8)
    words[0] = 1
    words[1] = type_id
    ffi.cast('uint64_t *', header + 16)[0] = ffi.cast('uintptr_t', address)
    words = ffi.cast('uint32_t *', header + 24)
    words[0] = total
    words[1] = instances
    file:write(ffi.string(header, 32))

    local ok, problem = api.capture(address, total, function(slice) file:write(slice) end)
    file:close()
    if not ok then return false, problem end
    return true, path
end

-- One place decides what a discovered buffer is called, whether it is new, and
-- whether it gets written to disk -- so the pointer scan and the memory sweep
-- cannot drift into reporting the same buffer two different ways.
local function record_buffer(api, state, key, address, total, type_id, instances, mixed, origin)
    if state.found[key] then return false end
    state.hits = state.hits + 1
    local name = FINGERPRINTS[total] or ('UNMATCHED_' .. total)
    state.found[key] = string.format('type 0x%08X  instances %6d  total %9d  = %s%s  (%s)',
                                     type_id, instances, total, name,
                                     mixed and ' [mixed type ids]' or '', origin)
    report(key .. ' -> ' .. state.found[key])
    if DUMP_THESE[name] and not state.files[name] then
        local ok, detail = write_dump(api, state, name, address, total, type_id, instances)
        state.files[name] = ok and detail or ('FAILED: ' .. tostring(detail))
        if ok then state.dumped = state.dumped + 1 end
        report(name .. ' dump: ' .. tostring(state.files[name]))
    end
    return true
end

-- ---------------------------------------------------------------------------

local scan_state
local function reset_scan()
    scan_state = {offset = 0, seen = {}, queue = {}, queue_at = 1}
end
reset_scan()

local function scan_chunks(api, game, state)
    for _ = 1, CHUNKS_PER_TICK do
        if scan_state.offset >= GLOBALS.size then return true end
        local size = math.min(CHUNK, GLOBALS.size - scan_state.offset)
        size = size - (size % 8)
        if size <= 0 then return true end
        local base = GLOBALS.rva + scan_state.offset
        if api.read_chunk(game + base, size) then
            for index = 0, size / 8 - 1 do
                local value = api.word(index)
                if value >= 0x10000ULL and value < 0x800000000000ULL and (value % 8ULL) == 0 then
                    local address = tonumber(value)
                    if not scan_state.seen[address] then
                        scan_state.seen[address] = base + index * 8
                        scan_state.queue[#scan_state.queue + 1] = address
                        state.candidates = state.candidates + 1
                    end
                end
            end
        end
        scan_state.offset = scan_state.offset + size
    end
    return false
end

local function probe_candidates(api, state)
    local processed = 0
    while scan_state.queue_at <= #scan_state.queue and processed < PROBES_PER_TICK do
        local address = scan_state.queue[scan_state.queue_at]
        scan_state.queue_at = scan_state.queue_at + 1
        processed = processed + 1
        state.probed = state.probed + 1

        local total, type_id, instances, mixed = measure(api, ffi.cast('uint8_t *', address))
        if not total then
            -- instances is the had_header flag on the failure path.
            if instances then note_reject(state, tostring(type_id)) end
        else
            record_buffer(api, state,
                          string.format('game.dll+0x%08X', scan_state.seen[address]),
                          ffi.cast('uint8_t *', address), total, type_id, instances, mixed,
                          'globals')
        end
    end
    return scan_state.queue_at > #scan_state.queue
end

-- Following pointers out of the globals array reaches 16 of the 54 shipped
-- settings files and nothing else -- with zero near misses, so nothing is being
-- rejected, those buffers simply are not referenced from there. The sweep drops
-- the pointer assumption entirely and looks for the header signature itself:
--     base +4  'LDLD'
--     base +8  version 1
-- anywhere in committed private memory.
local sweep_state

local function reset_sweep(api)
    sweep_state = {regions = api.regions(SWEEP_MIN_REGION), at = 1, offset = 0, bytes = 0}
end

local function sweep_memory(api, state)
    local budget = SWEEP_BYTES_PER_TICK
    while budget > 0 do
        local region = sweep_state.regions[sweep_state.at]
        if not region then return true end
        if sweep_state.offset >= region.size then
            sweep_state.at = sweep_state.at + 1
            sweep_state.offset = 0
        else
            local size = math.min(CHUNK, region.size - sweep_state.offset)
            size = size - (size % 4)
            if size < 32 then
                sweep_state.at = sweep_state.at + 1
                sweep_state.offset = 0
            else
                local at = region.base + sweep_state.offset
                if api.read_chunk(at, size) then
                    local words = api.scan32()
                    for index = 0, size / 4 - 2 do
                        if words[index] == DL_MAGIC and words[index + 1] == 1 then
                            -- The magic sits 4 bytes into the buffer, after the
                            -- instance count.
                            local base = at + index * 4 - 4
                            if sweep_state.offset + index * 4 >= 4 then
                                local total, type_id, instances, mixed = measure(api, base)
                                if total then
                                    state.sweep_hits = state.sweep_hits + 1
                                    record_buffer(api, state,
                                                  string.format('heap 0x%012X',
                                                                tonumber(ffi.cast('uintptr_t', base))),
                                                  base, total, type_id, instances, mixed, 'sweep')
                                end
                            end
                        end
                    end
                end
                -- Overlap by 8 bytes so a signature never straddles two reads.
                sweep_state.offset = sweep_state.offset + size - 8
                sweep_state.bytes = sweep_state.bytes + size
                budget = budget - size
            end
        end
    end
    return false
end

local function write_report(state)
    local loader = rawget(_G, 'CowboyBingusModLoader')
    local file = loader and loader.open_log and loader.open_log('HpmgDlHunt.log')
    if not file then return false end
    file:write(BUILD.revision .. '\n')
    file:write(string.format('phase=%s updates=%d cycles=%d candidates=%d probed=%d hits=%d near_misses=%d dumped=%d\n',
                             state.phase, state.updates, state.cycles, state.candidates,
                             state.probed, state.hits, state.near_misses, state.dumped))
    file:write(string.format('sweep: regions=%d scanned=%d MB signature_hits=%d\n',
                             state.sweep_regions, math.floor(state.sweep_bytes / 1048576),
                             state.sweep_hits))
    if state.build_note then file:write(state.build_note .. '\n') end

    file:write('\nDL settings buffers found:\n')
    local keys = {}
    for key in pairs(state.found) do keys[#keys + 1] = key end
    table.sort(keys)
    for _, key in ipairs(keys) do
        file:write(string.format('  %-26s %s\n', key, state.found[key]))
    end

    file:write('\nNear misses (had an LDLD header, then failed):\n')
    local reasons = {}
    for reason in pairs(state.rejects) do reasons[#reasons + 1] = reason end
    table.sort(reasons)
    if #reasons == 0 then file:write('  none\n') end
    for _, reason in ipairs(reasons) do
        file:write(string.format('  %6d x  %s\n', state.rejects[reason], reason))
    end

    file:write('\nDumps written:\n')
    local names = {}
    for name in pairs(state.files) do names[#names + 1] = name end
    table.sort(names)
    if #names == 0 then file:write('  none\n') end
    for _, name in ipairs(names) do
        file:write(string.format('  %-32s %s\n', name, state.files[name]))
    end
    file:close()
    return true
end

state.internals = {measure = measure, fingerprints = FINGERPRINTS, dump_these = DUMP_THESE,
                   globals = GLOBALS, max_instances = MAX_INSTANCES,
                   reset_sweep = reset_sweep, sweep_memory = sweep_memory,
                   record_buffer = record_buffer, chunk = CHUNK,
                   sweep_min_region = SWEEP_MIN_REGION}

-- ---------------------------------------------------------------------------

local previous_update = update
local self_update
local api, game
local idle = 0

self_update = function(dt, ...)
    state.updates = state.updates + 1

    if state.phase == 'waiting_for_update' then
        local ok, result, module = pcall(function()
            local created = create_api()
            local exe, dll = created.module(nil), created.module('game.dll')
            assert(exe and dll, 'Required game modules unavailable')
            assert(created.module_hash(exe) == BUILD.exe_sha256, 'Unsupported executable')
            assert(created.module_hash(dll) == BUILD.game_sha256, 'Unsupported game module')
            return created, dll
        end)
        if not ok then
            state.phase = 'failed: ' .. tostring(result)
            report(state.phase)
            pcall(write_report, state)
        else
            api, game = result, module
            state.build_note = 'Build matches Steam 24826606 / 1.8.45317.0.'
            state.phase = 'scanning'
            report('build verified; hunting, rescan every ' .. RESCAN_TICKS .. ' ticks')
        end

    elseif state.phase == 'scanning' then
        local ok, done = pcall(scan_chunks, api, game, state)
        if not ok then
            state.phase = 'failed: ' .. tostring(done)
            report(state.phase)
        elseif done then
            state.phase = 'probing'
        end

    elseif state.phase == 'probing' then
        local ok, done = pcall(probe_candidates, api, state)
        if not ok then
            state.phase = 'failed: ' .. tostring(done)
            report(state.phase)
        elseif done then
            local ready, problem = pcall(reset_sweep, api)
            if not ready then
                state.phase = 'failed: regions: ' .. tostring(problem)
                report(state.phase)
            else
                state.sweep_regions = #sweep_state.regions
                state.phase = 'sweeping'
                report(string.format('globals done (%d buffers); sweeping %d regions >= %d MB',
                                     state.hits, state.sweep_regions,
                                     math.floor(SWEEP_MIN_REGION / 1048576)))
            end
        end

    elseif state.phase == 'sweeping' then
        local ok, done = pcall(sweep_memory, api, state)
        if not ok then
            state.phase = 'failed: ' .. tostring(done)
            report(state.phase)
        else
            state.sweep_bytes = sweep_state.bytes
            if done then
                state.cycles = state.cycles + 1
                state.phase = 'idle'
                idle = 0
                pcall(write_report, state)
                report(string.format('cycle %d done: %d buffers (%d from sweep), %d near misses, %d dumps',
                                     state.cycles, state.hits, state.sweep_hits,
                                     state.near_misses, state.dumped))
            end
        end

    elseif state.phase == 'idle' then
        -- Settings load lazily, so look again later in the session.
        idle = idle + 1
        if idle >= RESCAN_TICKS then
            reset_scan()
            state.phase = 'scanning'
        end
    end

    if state.phase:find('^failed') then
        if update == self_update then update = previous_update or function() end end
    end

    if previous_update then return previous_update(dt, ...) end
end
update = self_update

report('loaded; waiting for the first update tick')
