-- HD2-Addon: mods/hpmg/dl_probe
--
-- L2 read-only probe: find every datalibrary (DL) settings buffer the game has
-- loaded, and the game.dll global that points at each one.
--
-- WHY THIS WORKS
--   game.dll is Themida/WinLicense packed (.winlice section, entry in .boot,
--   section entropy 8.0), so nothing can be read statically from the file. The
--   .dl_bin files on disk are encrypted too. But once the game decrypts a
--   settings blob into the heap it is plain datalibrary layout:
--
--     base +0   u32  instance count
--          +4   u32  0x444C444C  'LDLD'      <- per-instance header starts here
--          +8   u32  version (1)
--          +12  u32  root type id
--          +16  u32  payload size
--          +20  u32  is_64_bit_ptr (1)
--          +24  u32  reserved (0)
--          +28  root: [ptr to items][u32 item count]
--          ... next instance header follows the payload ...
--
--   BetterStratagemBounce reaches exactly one of these via game.dll+0x2791F68
--   and validates 11 instances of type 0x30EB6399 totalling 79296 bytes. That
--   is our ground truth: if this probe does not rediscover that buffer at that
--   RVA with that size, the probe is wrong and every other result is suspect.
--
--   Buffers are named by size. generated_stratagem_settings.dl_bin is 79344
--   bytes on disk and 79296 in memory, a constant 48 bytes of crypto framing,
--   so decrypted_size == file_size - 48 for each shipped settings file.
--
-- This module only ever reads. It never writes process memory.

if rawget(_G, 'HpmgDlProbe') then return end

local ffi = require('ffi')

local BUILD = {
    revision = 'dl_probe-1',
    exe_sha256 = 'A09FF52663E73B94FB0CAC0DCB5BA84FFD10ECF44F74A8921AC66AF923988CC3',
    game_sha256 = 'CC75948D90FDFDE259DCB519E9933DB7FFA3CCB281CE4FB89E6B1B011557470C',
}

-- The writable globals section of game.dll: VA 0x02394000, virtual size 7622788.
-- Every pointer the sample mods hardcode lives inside it.
local GLOBALS = {rva = 0x02394000, size = 7622788}

local DL_MAGIC = 0x444C444C
local MAX_INSTANCES = 512
local MAX_TOTAL = 64 * 1024 * 1024

-- Work budget per update tick. The probe must never stall a frame noticeably.
local CHUNK = 65536
local CHUNKS_PER_TICK = 8
local PROBES_PER_TICK = 3000

-- Generated by tools/gen_fingerprints.py; decrypted size -> settings file.
local FINGERPRINTS = {
    [24] = 'resource_swap',
    [108] = 'layer_package_indirection_settings',
    [116] = 'body_settings',
    [133] = 'stratagem_upgrade_settings',
    [180] = 'add_resource_dependencies',
    [364] = 'corporation_logos',
    [412] = 'route_settings',
    [480] = 'policy_settings',
    [604] = 'font_lookup',
    [812] = 'candidate_descs',
    [1124] = 'video_ui_settings',
    [1468] = 'distant_war_effect_settings',
    [1708] = 'arc_settings',
    [1764] = 'modifier_settings',
    [2172] = 'video_flow_settings',
    [3404] = 'beam_settings',
    [3728] = 'customization_passive_bonuses',
    [3948] = 'language_settings',
    [5980] = 'font_settings',
    [8716] = 'scenario_settings',
    [10014] = 'generation_settings',
    [10908] = 'status_effect_settings',
    [12062] = 'environment_settings',
    [12484] = 'sky_settings',
    [14444] = 'collision_event_settings',
    [16964] = 'planet_types_settings',
    [24508] = 'unit_customization_settings',
    [24636] = 'weather_color_set_settings',
    [28784] = 'weapon_customization_settings',
    [33146] = 'planet_override_settings',
    [48664] = 'damage_settings',
    [57164] = 'hit_effect_settings',
    [61485] = 'planet_region_settings',
    [61716] = 'unit_effect_settings',
    [66388] = 'explosion_settings',
    [79296] = 'stratagem_settings',
    [84489] = 'satellite_groups',
    [91764] = 'solar_system_settings',
    [93340] = 'projectile_settings',
    [142067] = 'galactic_presence_settings',
    [165268] = 'animation_event_trigger_settings',
    [213482] = 'weather_settings',
    [264723] = 'region_settings',
    [303564] = 'surface_effect_settings',
    [330082] = 'entity_deltas',
    [368228] = 'credits_settings',
    [375748] = 'customization_armor_sets',
    [393025] = 'location_groups',
    [481676] = 'planet_data',
    [512495] = 'zone_data',
    [673740] = 'stamp_settings',
    [1574628] = 'planet_territory_graphs',
    [1630059] = 'destruction_settings',
    [45630790] = 'entities',
}

-- RVAs already established by the sample mods, used to check our own output.
local GROUND_TRUTH = {
    [0x2791F68] = {name = 'stratagem_settings', type_id = 0x30EB6399, total = 79296,
                   source = 'BetterStratagemBounce'},
}

local state = {
    revision = BUILD.revision,
    phase = 'waiting_for_update',
    updates = 0,
    scanned = 0,
    candidates = 0,
    probed = 0,
    hits = 0,
    chunk_failures = 0,
}
rawset(_G, 'HpmgDlProbe', state)

local function report(message)
    print('[HpmgDlProbe] ' .. BUILD.revision .. ': ' .. message)
end

-- Struct tags are global to the LuaJIT VM and other CowboyBingus mods declare
-- their own copy of MEMORY_BASIC_INFORMATION, so this name must stay unique.
-- Duplicate *function* declarations with identical signatures are harmless.
local function create_api()
    assert(ffi.abi('64bit'), 'Windows x64 is required')
    ffi.cdef [[
        void *GetModuleHandleA(const char *name);
        uint32_t GetModuleFileNameW(void *module, uint16_t *path, uint32_t capacity);
        void *GetCurrentProcess(void);
        int ReadProcessMemory(void *process, const void *address, void *buffer, size_t size, size_t *read);
        void *CreateFileW(const uint16_t *path, uint32_t access, uint32_t share, void *security,
                          uint32_t disposition, uint32_t flags, void *template_file);
        int ReadFile(void *file, void *buffer, uint32_t size, uint32_t *read, void *overlapped);
        int CloseHandle(void *handle);
        int32_t BCryptOpenAlgorithmProvider(void **algorithm, const uint16_t *name,
                                            const uint16_t *provider, uint32_t flags);
        int32_t BCryptCloseAlgorithmProvider(void *algorithm, uint32_t flags);
        int32_t BCryptCreateHash(void *algorithm, void **hash, void *object, uint32_t object_size,
                                 const void *secret, uint32_t secret_size, uint32_t flags);
        int32_t BCryptHashData(void *hash, const void *data, uint32_t size, uint32_t flags);
        int32_t BCryptFinishHash(void *hash, void *digest, uint32_t size, uint32_t flags);
        int32_t BCryptDestroyHash(void *hash);
    ]]
    local kernel, bcrypt = ffi.load('kernel32'), ffi.load('bcrypt')
    local process = kernel.GetCurrentProcess()
    local api = {}

    local scan = ffi.new('uint8_t[?]', CHUNK)
    local scan_words = ffi.cast('uint64_t *', scan)
    local small = ffi.new('uint8_t[64]')
    local small_words = ffi.cast('uint32_t *', small)
    local count = ffi.new('size_t[1]')

    function api.module(name)
        local handle = kernel.GetModuleHandleA(name)
        if handle == nil then return nil end
        return ffi.cast('uint8_t *', handle)
    end

    -- Bulk read into the scan buffer; the caller reads it through scan_words.
    function api.read_chunk(address, size)
        if kernel.ReadProcessMemory(process, address, scan, size, count) == 0 then return false end
        return count[0] == size
    end

    function api.word(index) return scan_words[index] end

    -- Small read into the header buffer, exposed as u32 lanes.
    function api.read_header(address, size)
        if kernel.ReadProcessMemory(process, address, small, size, count) == 0 then return false end
        return count[0] == size
    end

    function api.header(index) return small_words[index] end

    function api.module_hash(module)
        local path = ffi.new('uint16_t[32768]')
        local length = kernel.GetModuleFileNameW(module, path, 32768)
        assert(length > 0 and length < 32768, 'Cannot resolve module file')
        local file = kernel.CreateFileW(path, 0x80000000, 7, nil, 3, 0x08000000, nil)
        assert(file ~= ffi.cast('void *', -1), 'Cannot read module file')
        local algorithm, hash = ffi.new('void *[1]'), ffi.new('void *[1]')
        local ok, result = pcall(function()
            local name = ffi.new('uint16_t[7]', {83, 72, 65, 50, 53, 54, 0})
            assert(bcrypt.BCryptOpenAlgorithmProvider(algorithm, name, nil, 0) == 0, 'SHA256 unavailable')
            assert(bcrypt.BCryptCreateHash(algorithm[0], hash, nil, 0, nil, 0, 0) == 0, 'SHA256 creation failed')
            local buffer, read = ffi.new('uint8_t[1048576]'), ffi.new('uint32_t[1]')
            while true do
                assert(kernel.ReadFile(file, buffer, 1048576, read, nil) ~= 0, 'Module file read failed')
                if read[0] == 0 then break end
                assert(bcrypt.BCryptHashData(hash[0], buffer, read[0], 0) == 0, 'SHA256 update failed')
            end
            local digest, hex = ffi.new('uint8_t[32]'), {}
            assert(bcrypt.BCryptFinishHash(hash[0], digest, 32, 0) == 0, 'SHA256 finish failed')
            for i = 0, 31 do hex[#hex + 1] = string.format('%02X', digest[i]) end
            return table.concat(hex)
        end)
        if hash[0] ~= nil then bcrypt.BCryptDestroyHash(hash[0]) end
        if algorithm[0] ~= nil then bcrypt.BCryptCloseAlgorithmProvider(algorithm[0], 0) end
        kernel.CloseHandle(file)
        if not ok then error(result) end
        return result
    end

    return api
end

-- Walk the instance chain at `address` and return its total byte size, the root
-- type id, and the instance count -- or nil with a reason.
local function measure(api, address)
    if not api.read_header(address, 28) then return nil, 'unreadable' end
    local instances = api.header(0)
    if instances < 1 or instances > MAX_INSTANCES then return nil, 'count' end
    if api.header(1) ~= DL_MAGIC then return nil, 'magic' end
    if api.header(2) ~= 1 then return nil, 'version' end
    if api.header(5) ~= 1 then return nil, 'not 64-bit' end
    if api.header(6) ~= 0 then return nil, 'reserved' end

    local type_id = api.header(3)
    local offset = 4
    local mixed = false
    for _ = 1, instances do
        if not api.read_header(address + offset, 24) then return nil, 'chain unreadable' end
        if api.header(0) ~= DL_MAGIC then return nil, 'chain magic' end
        if api.header(1) ~= 1 then return nil, 'chain version' end
        if api.header(2) ~= type_id then mixed = true end
        if api.header(4) ~= 1 then return nil, 'chain not 64-bit' end
        local payload = api.header(3)
        offset = offset + 24 + payload
        if offset > MAX_TOTAL then return nil, 'oversize' end
    end
    return offset, type_id, instances, mixed
end

local function describe(total, type_id, instances, mixed)
    local label = FINGERPRINTS[total]
    local note
    if label then
        note = label
    else
        note = 'UNMATCHED (no shipped .dl_bin is ' .. tostring(total + 48) .. ' bytes)'
    end
    if mixed then note = note .. ' [mixed type ids]' end
    return string.format('type 0x%08X  instances %3d  total %9d  = %s',
                         type_id, instances, total, note)
end

-- Exposed so tests/test_dl_probe.lua can drive the parser against synthetic
-- buffers, the way the sample mods test their layouts without attaching to the
-- game. Carrying these references costs nothing at runtime.
state.internals = {measure = measure, describe = describe, fingerprints = FINGERPRINTS,
                   ground_truth = GROUND_TRUTH, globals = GLOBALS}

local function write_report(state)
    local loader = rawget(_G, 'CowboyBingusModLoader')
    local file = loader and loader.open_log and loader.open_log('HpmgDlProbe.log')
    if not file then return false end
    file:write(BUILD.revision .. '\n')
    file:write(string.format('phase=%s updates=%d scanned=%d candidates=%d probed=%d hits=%d chunk_failures=%d\n',
                             state.phase, state.updates, state.scanned, state.candidates,
                             state.probed, state.hits, state.chunk_failures))
    if state.build_note then file:write(state.build_note .. '\n') end
    file:write('\nDL settings buffers reachable from game.dll globals:\n')
    local rows = state.results or {}
    table.sort(rows, function(a, b) return a.rva < b.rva end)
    for _, row in ipairs(rows) do
        file:write(string.format('  game.dll+0x%08X -> 0x%012X  %s\n',
                                 row.rva, row.address, row.text))
    end
    file:write('\nGround truth check:\n')
    for rva, expected in pairs(GROUND_TRUTH) do
        local found
        for _, row in ipairs(rows) do
            if row.rva == rva then found = row end
        end
        if not found then
            file:write(string.format('  FAIL game.dll+0x%08X not rediscovered (%s says %s, %d bytes)\n',
                                     rva, expected.source, expected.name, expected.total))
        elseif found.total == expected.total and found.type_id == expected.type_id then
            file:write(string.format('  PASS game.dll+0x%08X  %s  type 0x%08X  %d bytes, agrees with %s\n',
                                     rva, expected.name, expected.type_id, expected.total, expected.source))
        else
            file:write(string.format('  FAIL game.dll+0x%08X  got type 0x%08X %d bytes, expected type 0x%08X %d bytes\n',
                                     rva, found.type_id, found.total, expected.type_id, expected.total))
        end
    end
    file:close()
    return true
end

-- ---------------------------------------------------------------------------

local scan_state = {offset = 0, seen = {}, queue = {}, queue_at = 1}

local function begin(state)
    local api = create_api()
    local exe, game = api.module(nil), api.module('game.dll')
    assert(exe and game, 'Required game modules unavailable')
    local exe_hash, game_hash = api.module_hash(exe), api.module_hash(game)
    if exe_hash ~= BUILD.exe_sha256 or game_hash ~= BUILD.game_sha256 then
        state.build_note = 'Unsupported build; RVAs below mean nothing. exe='
            .. exe_hash:sub(1, 16) .. ' game=' .. game_hash:sub(1, 16)
        return nil
    end
    state.build_note = 'Build matches the supported Steam 24826606 / 1.8.45317.0 image.'
    return api, game
end

-- Collect pointer-shaped qwords out of the globals section, a few chunks per tick.
local function scan_chunks(api, game, state)
    for _ = 1, CHUNKS_PER_TICK do
        if scan_state.offset >= GLOBALS.size then return true end
        local size = math.min(CHUNK, GLOBALS.size - scan_state.offset)
        size = size - (size % 8)
        if size <= 0 then return true end
        local base = GLOBALS.rva + scan_state.offset
        if api.read_chunk(game + base, size) then
            for index = 0, size / 8 - 1 do
                local value = api.word(index)
                -- Heap allocations are at least 8-byte aligned; the upper bound
                -- is the Windows x64 user-mode limit.
                if value >= 0x10000ULL and value < 0x800000000000ULL
                    and (value % 8ULL) == 0 then
                    local address = tonumber(value)
                    if not scan_state.seen[address] then
                        scan_state.seen[address] = base + index * 8
                        scan_state.queue[#scan_state.queue + 1] = address
                        state.candidates = state.candidates + 1
                    end
                end
            end
        else
            state.chunk_failures = state.chunk_failures + 1
        end
        scan_state.offset = scan_state.offset + size
        state.scanned = scan_state.offset
    end
    return false
end

-- Test queued candidates against the DL header signature, a batch per tick.
local function probe_candidates(api, state)
    local processed = 0
    while scan_state.queue_at <= #scan_state.queue and processed < PROBES_PER_TICK do
        local address = scan_state.queue[scan_state.queue_at]
        scan_state.queue_at = scan_state.queue_at + 1
        processed = processed + 1
        state.probed = state.probed + 1
        local total, type_id, instances, mixed = measure(api, ffi.cast('uint8_t *', address))
        if total then
            state.hits = state.hits + 1
            state.results[#state.results + 1] = {
                rva = scan_state.seen[address],
                address = address,
                total = total,
                type_id = type_id,
                text = describe(total, type_id, instances, mixed),
            }
        end
    end
    return scan_state.queue_at > #scan_state.queue
end

-- ---------------------------------------------------------------------------

local previous_update = update
local self_update
local api, game

self_update = function(dt, ...)
    state.updates = state.updates + 1

    if state.phase == 'waiting_for_update' then
        state.phase = 'verifying_build'
        local ok, result, module = pcall(begin, state)
        if not ok then
            state.phase = 'failed: ' .. tostring(result)
            report(state.phase)
            pcall(write_report, state)
        elseif not result then
            state.phase = 'unsupported_build'
            report(state.phase)
            pcall(write_report, state)
        else
            api, game = result, module
            state.results = {}
            state.phase = 'scanning_globals'
            report('build verified; scanning ' .. GLOBALS.size .. ' bytes of globals')
        end
    elseif state.phase == 'scanning_globals' then
        local ok, done = pcall(scan_chunks, api, game, state)
        if not ok then
            state.phase = 'failed: ' .. tostring(done)
            report(state.phase)
            pcall(write_report, state)
        elseif done then
            state.phase = 'probing_candidates'
            report(string.format('scan complete: %d candidate pointers from %d bytes (%d unreadable chunks)',
                                 state.candidates, state.scanned, state.chunk_failures))
        end
    elseif state.phase == 'probing_candidates' then
        local ok, done = pcall(probe_candidates, api, state)
        if not ok then
            state.phase = 'failed: ' .. tostring(done)
            report(state.phase)
            pcall(write_report, state)
        elseif done then
            state.phase = 'complete'
            report(string.format('found %d DL settings buffers from %d probes', state.hits, state.probed))
            if pcall(write_report, state) then
                report('wrote HpmgDlProbe.log')
            end
        end
    end

    -- Finished or failed: stop costing frames, but only release the callback
    -- while we still own it. A later mod may have wrapped us since load.
    if state.phase == 'complete' or state.phase:find('^failed') or state.phase == 'unsupported_build' then
        if update == self_update then update = previous_update or function() end end
    end

    if previous_update then return previous_update(dt, ...) end
end
update = self_update

report('loaded; waiting for the first update tick')
