"""Emit a Lua size-fingerprint table for the game's encrypted settings files.

The .dl_bin files on disk are encrypted (entropy ~8.0), but their sizes are not.
generated_stratagem_settings.dl_bin is 79,344 bytes and BetterStratagemBounce's
verified in-memory buffer is 79,296 -- a constant 48 bytes of crypto framing.

So: decrypted_size == file_size - FRAMING. That equation is confirmed on exactly
one file, which is enough to be worth testing and not enough to be trusted. The
runtime probe prints both the matched and unmatched buffers so the hypothesis
gets checked against every settings buffer the game actually loads.

Usage:
    py -3 -B tools/gen_fingerprints.py [--game-dir <path>] [--framing 48]
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRAMING = 48
# The one file whose decrypted size we know independently.
ANCHOR = ('generated_stratagem_settings.dl_bin', 79344, 79296)


def read_game_dir():
    config = ROOT / 'mods.json'
    if config.is_file():
        return json.loads(config.read_text(encoding='utf-8')).get('game_dir')
    return None


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--game-dir', type=Path, default=Path(read_game_dir() or '.'))
    parser.add_argument('--framing', type=int, default=FRAMING)
    parser.add_argument('--min-size', type=int, default=0)
    args = parser.parse_args()

    game_data = args.game_dir / 'data' / 'game'
    if not game_data.is_dir():
        raise SystemExit('not found: %s' % game_data)

    name, file_size, known = ANCHOR
    anchor = game_data / name
    if anchor.is_file() and anchor.stat().st_size != file_size:
        print('-- WARNING: %s is %d bytes, expected %d; the game was updated and'
              % (name, anchor.stat().st_size, file_size))
        print('-- every RVA and fingerprint in this project must be revalidated.')
    elif anchor.is_file():
        print('-- Anchor check: %s = %d bytes, %d - %d = %d (matches the verified buffer).'
              % (name, file_size, file_size, args.framing, file_size - args.framing))

    entries = []
    for path in sorted(game_data.glob('*.dl_bin')):
        size = path.stat().st_size
        if size < args.min_size:
            continue
        label = path.stem
        if label.startswith('generated_'):
            label = label[len('generated_'):]
        entries.append((size - args.framing, label, size))

    entries.sort()
    print('-- Generated by tools/gen_fingerprints.py; decrypted size -> settings file.')
    print('-- %d entries, framing %d bytes.' % (len(entries), args.framing))
    print('local FINGERPRINTS = {')
    for decrypted, label, size in entries:
        print("    [%d] = '%s'," % (decrypted, label))
    print('}')

    collisions = {}
    for decrypted, label, _ in entries:
        collisions.setdefault(decrypted, []).append(label)
    duplicated = {k: v for k, v in collisions.items() if len(v) > 1}
    if duplicated:
        print('\n-- Ambiguous sizes (probe must disambiguate by type id):')
        for size, labels in sorted(duplicated.items()):
            print('--   %d -> %s' % (size, ', '.join(labels)))


if __name__ == '__main__':
    main()
